"""Seed training data for the intent classifier.

Each entry is (utterance, intent). The classifier generalizes from these;
the learner layer extends this set with user-taught and feedback examples.
The "chat" class anchors conversational text so commands and chat separate.
"""

SEED_INTENTS = [
    # system
    ("shut down the computer", "system_shutdown"),
    ("power off the pc", "system_shutdown"),
    ("turn the computer off", "system_shutdown"),
    ("restart the computer", "system_restart"),
    ("reboot the system", "system_restart"),
    ("put the computer to sleep", "system_sleep"),
    ("lock the screen", "system_lock"),
    ("mute the volume", "system_mute"),
    ("turn the volume up", "system_volume_up"),
    ("make it louder", "system_volume_up"),
    ("lower the volume", "system_volume_down"),
    ("increase the brightness", "system_brightness_up"),
    ("decrease the brightness", "system_brightness_down"),
    # info
    ("what time is it", "info_time"),
    ("what is the current time", "info_time"),
    ("current time please", "info_time"),
    ("tell me the time now", "info_time"),
    ("time check", "info_time"),
    ("what is the date today", "info_date"),
    ("what day is it", "info_date"),
    ("current date please", "info_date"),
    ("what is the weather outside", "info_weather"),
    ("how is the weather today", "info_weather"),
    ("how are you feeling today", "info_health"),
    # email
    ("read my emails", "email_read"),
    ("check my inbox", "email_read"),
    ("show me new mail", "email_read"),
    ("write an email", "email_write"),
    ("compose a new email to someone", "email_write"),
    ("send an email", "email_write"),
    ("summarize my emails", "email_summarize"),
    ("give me an email summary", "email_summarize"),
    # media
    ("play some music", "media_play"),
    ("start playing music", "media_play"),
    ("pause the music", "media_pause"),
    ("skip to the next song", "media_next"),
    ("go back to the previous track", "media_previous"),
    ("stop the music", "media_stop"),
    # smart home
    ("turn on the lights", "smart_home_turn_on"),
    ("switch on the kitchen lights", "smart_home_turn_on"),
    ("turn off the bedroom light", "smart_home_turn_off"),
    ("lock the front door", "smart_home_lock_door"),
    ("set the thermostat to 72", "smart_home_set_thermostat"),
    ("set the temperature to 68", "smart_home_set_thermostat"),
    # browser / web
    ("open youtube", "browser_navigate"),
    ("go to google", "browser_navigate"),
    ("open the website", "browser_navigate"),
    ("search youtube for something", "browser_youtube"),
    ("play a video on youtube", "browser_youtube"),
    ("search the web for something", "browser_google"),
    ("google this", "browser_google"),
    # files / docs
    ("open a file", "file_open"),
    ("find a file on the computer", "file_find"),
    ("list the files in a folder", "file_list"),
    ("create a new word document", "docs_new"),
    ("make a word document", "docs_new"),
    ("edit the word document", "docs_edit"),
    # code
    ("scaffold a python app", "code_scaffold"),
    ("create a flutter project", "code_scaffold"),
    ("make a web app", "code_scaffold"),
    # camera / cctv / vision
    ("take a picture with the camera", "camera_capture"),
    ("take a photo", "camera_capture"),
    ("show me the cctv feed", "cctv_view"),
    ("view the security cameras", "cctv_view"),
    ("analyze the camera feed", "cctv_analyze"),
    ("check the security feed", "cctv_analyze"),
    ("who is that person", "vision_identify"),
    ("recognize this face", "vision_identify"),
    # mobile
    ("list my connected devices", "adb_devices"),
    ("show my phones", "adb_devices"),
    ("take a screenshot of the phone", "adb_screen"),
    # scheduler
    ("remind me to call mom", "scheduler_reminder"),
    ("remind me to buy groceries", "scheduler_reminder"),
    ("set an alarm for seven", "scheduler_alarm"),
    ("set an alarm at 7 am", "scheduler_alarm"),
    # personality
    ("be more sarcastic", "set_personality"),
    ("be less formal", "set_personality"),
    ("talk with more humor", "set_personality"),
    ("teach you something new", "teach_skill"),
    ("learn this command", "teach_skill"),
    ("i will show you how to do this", "teach_skill"),
    # social
    ("hello jarvis", "greeting"),
    ("hi there", "greeting"),
    ("good morning", "greeting"),
    ("thank you jarvis", "thanks"),
    ("thanks for the help", "thanks"),
    ("goodbye", "goodbye"),
    ("see you later", "goodbye"),
    ("tell me a joke", "joke"),
    ("make me laugh", "joke"),
    # chat anchors
    ("what is the meaning of life", "chat"),
    ("tell me a story about a dragon", "chat"),
    ("what do you think about the universe", "chat"),
    ("explain quantum physics to me", "chat"),
    ("what is your favorite color", "chat"),
    ("tell me about yourself", "chat"),
    ("can we talk about movies", "chat"),
    ("what should i have for dinner", "chat"),
    ("do you believe in aliens", "chat"),
    ("how does a car engine work", "chat"),
    ("teach me something interesting", "chat"),
    ("teach me about the stars", "chat"),
    ("educate me on history", "chat"),
]
