"""Code skills: scaffold generation for building apps from a voice command.

Scaffolding is deterministic (templates). For complex generation the chat
model can be consulted when available.
"""

import datetime
import os
from typing import Any, Dict

_TEMPLATES = {
    "python": {
        "app.py": "def main():\n    print('J.A.R.V.I.S. generated project')\n\n\nif __name__ == '__main__':\n    main()\n",
        "requirements.txt": "fastapi>=0.115.0\nuvicorn[standard]>=0.30.0\n",
        "README.md": "# {name}\n\nGenerated by J.A.R.V.I.S.\n",
    },
    "web": {
        "index.html": "<!DOCTYPE html>\n<html>\n<head><title>{name}</title></head>\n<body><h1>{name}</h1></body>\n</html>\n",
        "style.css": "body { font-family: sans-serif; }\n",
        "app.js": "console.log('J.A.R.V.I.S. web app');\n",
    },
    "flutter": {
        "pubspec.yaml": "name: {name_snake}\ndescription: Generated by J.A.R.V.I.S.\n",
        "lib/main.dart": "import 'package:flutter/material.dart';\n\nvoid main() => runApp(App());\n\nclass App extends StatelessWidget {\n  @override\n  Widget build(BuildContext context) {\n    return MaterialApp(home: Scaffold(body: Center(child: Text('{name}'))));\n  }\n}\n",
    },
    "node": {
        "index.js": "const express = require('express');\nconst app = express();\napp.listen(3000, () => console.log('J.A.R.V.I.S. server on 3000'));\n",
        "package.json": '{\n  "name": "{name_snake}",\n  "main": "index.js"\n}\n',
        "README.md": "# {name}\n",
    },
}


def _slug(name: str) -> str:
    return "".join(c if c.isalnum() else "_" for c in (name or "app").lower())


async def code_scaffold(params: Dict[str, Any], ctx: Any) -> Dict[str, Any]:
    language = (params.get("language") or params.get("kind") or "python").lower()
    name = params.get("name") or params.get("app_name") or "jarvis_app"
    template = _TEMPLATES.get(language)
    if not template:
        return {"success": False,
                "narration": f"I can scaffold python, web, flutter, or node. You asked for '{language}'.",
                "type": "code_result"}

    out_dir = getattr(ctx, "kernel", None) and ctx.kernel.cfg.data_dir / "projects" / _slug(name) \
        or os.path.join("projects", _slug(name))
    os.makedirs(out_dir, exist_ok=True)
    created = []
    for fname, content in template.items():
        filled = content.format(name=name, name_snake=_slug(name))
        with open(os.path.join(out_dir, fname), "w", encoding="utf-8") as f:
            f.write(filled)
        created.append(fname)

    narration = (f"Created a {language} project in {out_dir}: "
                 + ", ".join(created) + ". Say 'open it' and I'll show the files.")
    return {"success": True, "narration": narration, "type": "code_result",
            "data": {"language": language, "dir": str(out_dir), "files": created}}


def register(reg) -> None:
    reg.skill("code_scaffold", code_scaffold, description="Scaffold an app project (python/web/flutter/node)")
